curstarts:
  - scMin: [ 1, 1, 1, 1] 
    scMax: [ 7, 7, 7, 7]
  - scMin: [ 1, 1, 7, 1] 
    scMax: [ 7, 7,13, 7]
  - scMin: [ 1, 1,11, 1]
    scMax: [ 7, 7,26, 7]
  - scMin: [ 1, 1, 1, 1]
    scMax: [ 7, 7,26, 7]
  - scMin: [ 1, 1,11, 1]
    scMax: [ 7, 7,15, 7]
  - scMin: [ 7, 1, 1, 1] 
    scMax: [13, 7, 7, 7]
  - scMin: [ 7, 1, 7, 1] 
    scMax: [13, 7,13, 7]
  - scMin: [ 7, 1,11, 1]
    scMax: [13, 7,26, 7]
  - scMin: [ 7, 1, 1, 1]
    scMax: [13, 7,26, 7]
  - scMin: [ 7, 1,11, 1]
    scMax: [13, 7,15, 7]
  - scMin: [11, 1, 1, 1] 
    scMax: [26, 7, 7, 7]
  - scMin: [11, 1, 7, 1] 
    scMax: [26, 7,13, 7]
  - scMin: [11, 1,11, 1]
    scMax: [26, 7,26, 7]
  - scMin: [11, 1, 1, 1]
    scMax: [26, 7,26, 7]
  - scMin: [11, 1,11, 1]
    scMax: [26, 7,15, 7]
  - scMin: [ 1, 1, 1, 1] 
    scMax: [26, 7, 7, 7]
  - scMin: [ 1, 1, 7, 1] 
    scMax: [26, 7,13, 7]
  - scMin: [ 1, 1,11, 1]
    scMax: [26, 7,26, 7]
  - scMin: [ 1, 1, 1, 1]
    scMax: [26, 7,26, 7]
  - scMin: [ 1, 1,11, 1]
    scMax: [26, 7,15, 7]
  - scMin: [11, 1, 1, 1] 
    scMax: [15, 7, 7, 7]
  - scMin: [11, 1, 7, 1] 
    scMax: [15, 7,13, 7]
  - scMin: [11, 1,11, 1]
    scMax: [15, 7,26, 7]
  - scMin: [11, 1, 1, 1]
    scMax: [15, 7,26, 7]
  - scMin: [11, 1,11, 1]
    scMax: [15, 7,15, 7]
  - scMin: [ 1, 7, 1, 7] 
    scMax: [ 7,13, 7,13]
  - scMin: [ 1, 7, 7, 7] 
    scMax: [ 7,13,13,13]
  - scMin: [ 1, 7,11, 7]
    scMax: [ 7,13,26,13]
  - scMin: [ 1, 7, 1, 7]
    scMax: [ 7,13,26,13]
  - scMin: [ 1, 7,11, 7]
    scMax: [ 7,13,15,13]
  - scMin: [ 7, 7, 1, 7] 
    scMax: [13,13, 7,13]
  - scMin: [ 7, 7, 7, 7] 
    scMax: [13,13,13,13]
  - scMin: [ 7, 7,11, 7]
    scMax: [13,13,26,13]
  - scMin: [ 7, 7, 1, 7]
    scMax: [13,13,26,13]
  - scMin: [ 7, 7,11, 7]
    scMax: [13,13,15,13]
  - scMin: [11, 7, 1, 7] 
    scMax: [26,13, 7,13]
  - scMin: [11, 7, 7, 7] 
    scMax: [26,13,13,13]
  - scMin: [11, 7,11, 7]
    scMax: [26,13,26,13]
  - scMin: [11, 7, 1, 7]
    scMax: [26,13,26,13]
  - scMin: [11, 7,11, 7]
    scMax: [26,13,15,13]
  - scMin: [ 1, 7, 1, 7] 
    scMax: [26,13, 7,13]
  - scMin: [ 1, 7, 7, 7] 
    scMax: [26,13,13,13]
  - scMin: [ 1, 7,11, 7]
    scMax: [26,13,26,13]
  - scMin: [ 1, 7, 1, 7]
    scMax: [26,13,26,13]
  - scMin: [ 1, 7,11, 7]
    scMax: [26,13,15,13]
  - scMin: [11, 7, 1, 7] 
    scMax: [15,13, 7,13]
  - scMin: [11, 7, 7, 7] 
    scMax: [15,13,13,13]
  - scMin: [11, 7,11, 7]
    scMax: [15,13,26,13]
  - scMin: [11, 7, 1, 7]
    scMax: [15,13,26,13]
  - scMin: [11, 7,11, 7]
    scMax: [15,13,15,13]
  - scMin: [ 1,11, 1,11] 
    scMax: [ 7,26, 7,26]
  - scMin: [ 1,11, 7,11] 
    scMax: [ 7,26,13,26]
  - scMin: [ 1,11,11,11]
    scMax: [ 7,26,26,26]
  - scMin: [ 1,11, 1,11]
    scMax: [ 7,26,26,26]
  - scMin: [ 1,11,11,11]
    scMax: [ 7,26,15,26]
  - scMin: [ 7,11, 1,11] 
    scMax: [13,26, 7,26]
  - scMin: [ 7,11, 7,11] 
    scMax: [13,26,13,26]
  - scMin: [ 7,11,11,11]
    scMax: [13,26,26,26]
  - scMin: [ 7,11, 1,11]
    scMax: [13,26,26,26]
  - scMin: [ 7,11,11,11]
    scMax: [13,26,15,26]
  - scMin: [11,11, 1,11] 
    scMax: [26,26, 7,26]
  - scMin: [11,11, 7,11] 
    scMax: [26,26,13,26]
  - scMin: [11,11,11,11]
    scMax: [26,26,26,26]
  - scMin: [11,11, 1,11]
    scMax: [26,26,26,26]
  - scMin: [11,11,11,11]
    scMax: [26,26,15,26]
  - scMin: [ 1,11, 1,11] 
    scMax: [26,26, 7,26]
  - scMin: [ 1,11, 7,11] 
    scMax: [26,26,13,26]
  - scMin: [ 1,11,11,11]
    scMax: [26,26,26,26]
  - scMin: [ 1,11, 1,11]
    scMax: [26,26,26,26]
  - scMin: [ 1,11,11,11]
    scMax: [26,26,15,26]
  - scMin: [11,11, 1,11] 
    scMax: [15,26, 7,26]
  - scMin: [11,11, 7,11] 
    scMax: [15,26,13,26]
  - scMin: [11,11,11,11]
    scMax: [15,26,26,26]
  - scMin: [11,11, 1,11]
    scMax: [15,26,26,26]
  - scMin: [11,11,11,11]
    scMax: [15,26,15,26]
  - scMin: [ 1, 1, 1, 1] 
    scMax: [ 7,26, 7,26]
  - scMin: [ 1, 1, 7, 1] 
    scMax: [ 7,26,13,26]
  - scMin: [ 1, 1,11, 1]
    scMax: [ 7,26,26,26]
  - scMin: [ 1, 1, 1, 1]
    scMax: [ 7,26,26,26]
  - scMin: [ 1, 1,11, 1]
    scMax: [ 7,26,15,26]
  - scMin: [ 7, 1, 1, 1] 
    scMax: [13,26, 7,26]
  - scMin: [ 7, 1, 7, 1] 
    scMax: [13,26,13,26]
  - scMin: [ 7, 1,11, 1]
    scMax: [13,26,26,26]
  - scMin: [ 7, 1, 1, 1]
    scMax: [13,26,26,26]
  - scMin: [ 7, 1,11, 1]
    scMax: [13,26,15,26]
  - scMin: [11, 1, 1, 1] 
    scMax: [26,26, 7,26]
  - scMin: [11, 1, 7, 1] 
    scMax: [26,26,13,26]
  - scMin: [11, 1,11, 1]
    scMax: [26,26,26,26]
  - scMin: [11, 1, 1, 1]
    scMax: [26,26,26,26]
  - scMin: [11, 1,11, 1]
    scMax: [26,26,15,26]
  - scMin: [ 1, 1, 1, 1] 
    scMax: [26,26, 7,26]
  - scMin: [ 1, 1, 7, 1] 
    scMax: [26,26,13,26]
  - scMin: [ 1, 1,11, 1]
    scMax: [26,26,26,26]
  - scMin: [ 1, 1, 1, 1]
    scMax: [26,26,26,26]
  - scMin: [ 1, 1,11, 1]
    scMax: [26,26,15,26]
  - scMin: [11, 1, 1, 1] 
    scMax: [15,26, 7,26]
  - scMin: [11, 1, 7, 1] 
    scMax: [15,26,13,26]
  - scMin: [11, 1,11, 1]
    scMax: [15,26,26,26]
  - scMin: [11, 1, 1, 1]
    scMax: [15,26,26,26]
  - scMin: [11, 1,11, 1]
    scMax: [15,26,15,26]
  - scMin: [ 1,11, 1,11] 
    scMax: [ 7,15, 7,15]
  - scMin: [ 1,11, 7,11] 
    scMax: [ 7,15,13,15]
  - scMin: [ 1,11,11,11]
    scMax: [ 7,15,26,15]
  - scMin: [ 1,11, 1,11]
    scMax: [ 7,15,26,15]
  - scMin: [ 1,11,11,11]
    scMax: [ 7,15,15,15]
  - scMin: [ 7,11, 1,11] 
    scMax: [13,15, 7,15]
  - scMin: [ 7,11, 7,11] 
    scMax: [13,15,13,15]
  - scMin: [ 7,11,11,11]
    scMax: [13,15,26,15]
  - scMin: [ 7,11, 1,11]
    scMax: [13,15,26,15]
  - scMin: [ 7,11,11,11]
    scMax: [13,15,15,15]
  - scMin: [11,11, 1,11] 
    scMax: [26,15, 7,15]
  - scMin: [11,11, 7,11] 
    scMax: [26,15,13,15]
  - scMin: [11,11,11,11]
    scMax: [26,15,26,15]
  - scMin: [11,11, 1,11]
    scMax: [26,15,26,15]
  - scMin: [11,11,11,11]
    scMax: [26,15,15,15]
  - scMin: [ 1,11, 1,11] 
    scMax: [26,15, 7,15]
  - scMin: [ 1,11, 7,11] 
    scMax: [26,15,13,15]
  - scMin: [ 1,11,11,11]
    scMax: [26,15,26,15]
  - scMin: [ 1,11, 1,11]
    scMax: [26,15,26,15]
  - scMin: [ 1,11,11,11]
    scMax: [26,15,15,15]
  - scMin: [11,11, 1,11] 
    scMax: [15,15, 7,15]
  - scMin: [11,11, 7,11] 
    scMax: [15,15,13,15]
  - scMin: [11,11,11,11]
    scMax: [15,15,26,15]
  - scMin: [11,11, 1,11]
    scMax: [15,15,26,15]
  - scMin: [11,11,11,11]
    scMax: [15,15,15,15]
simNumber:
  - [296]
  - [297]
  - [298]
  - [299]
  - [300]
  - [301]
  - [302]
  - [303]
  - [304]
  - [305]
  - [306]
  - [307]
  - [308]
  - [309]
  - [310]
  - [311]
  - [312]
  - [313]
  - [314]
  - [315]
  - [316]
  - [317]
  - [318]
  - [319]
  - [320]
  - [321]
  - [322]
  - [323]
  - [324]
  - [325]
  - [326]
  - [327]
  - [328]
  - [329]
  - [330]
  - [331]
  - [332]
  - [333]
  - [334]
  - [335]
  - [336]
  - [337]
  - [338]
  - [339]
  - [340]
  - [341]
  - [342]
  - [343]
  - [344]
  - [345]
  - [346]
  - [347]
  - [348]
  - [349]
  - [350]
  - [351]
  - [352]
  - [353]
  - [354]
  - [355]
  - [356]
  - [357]
  - [358]
  - [359]
  - [360]
  - [361]
  - [362]
  - [363]
  - [364]
  - [365]
  - [366]
  - [367]
  - [368]
  - [369]
  - [370]
  - [371]
  - [372]
  - [373]
  - [374]
  - [375]
  - [376]
  - [377]
  - [378]
  - [379]
  - [380]
  - [381]
  - [382]
  - [383]
  - [384]
  - [385]
  - [386]
  - [387]
  - [388]
  - [389]
  - [390]
  - [391]
  - [392]
  - [393]
  - [394]
  - [395]
  - [396]
  - [397]
  - [398]
  - [399]
  - [400]
  - [401]
  - [402]
  - [403]
  - [404]
  - [405]
  - [406]
  - [407]
  - [408]
  - [409]
  - [410]
  - [411]
  - [412]
  - [413]
  - [414]
  - [415]
  - [416]
  - [417]
  - [418]
  - [419]
  - [420]
runLength: '2k'
SylLearnStyle: 'nsL'
vertObLearn:
  vertical:
    learn: [0.95]
    invent: [0.1]
  oblique:
    learn: [0.1]
    invent: [0.01]
sylDist: 'oppsyl'
curinh_value: [0.95]
num_pop: [2]
pop_size: [400]
sylnum: [156]
num_sylls_per_prob_lvl: [12]
number_of_reps: [10]
standard_deviation: [2]

# curinh.pattern - calling either the row number 
# or name of row for different curiosity inheritance patterns - 
# 1: father; 2: mother; 3: same; 4:opposite
curinh_pattern: [2]
one_pop_singers: [10, 10]
